workspace:
  base: /build
  path: src/github.com/ukhomeoffice/cop-private-translation-service

pipeline:
  test:
    image: node:8
    commands:
      - npm install
      - npm run coverage
    when:
      event:
      - push
      - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-private-translation-service
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch:
        - master
      event:
        - push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_INTERNAL_CA_URL
      - DEV_NO_LOGGING_URL_PARAMS
      - DEV_NO_LOGGING_BODY
      - DEV_NO_LOGGING_RESPONSE
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_KEYCLOAK_SECRET
      - DEV_PRIVATE_FORM_NAME
      - DEV_PRIVATE_WORKFLOW_ENGINE_NAME
      - DEV_PRIVATE_UI_NAME
      - DEV_INT_DOMAIN
      - DEV_EXT_DOMAIN
      - DEV_PROTOCOL
      - DEV_SESSION_NAME
      - DEV_SESSION_SECRET
    commands:
      - export NAME=$${DEV_NAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${DEV_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${DEV_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${DEV_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${DEV_NO_LOGGING_RESPONSE}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${DEV_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${DEV_INT_DOMAIN}
      - export EXT_DOMAIN=$${DEV_EXT_DOMAIN}
      - export PROTOCOL=$${DEV_PROTOCOL}
      - export PRIVATE_FORM_NAME=$${DEV_PRIVATE_FORM_NAME}
      - export PRIVATE_WORKFLOW_ENGINE_NAME=$${DEV_PRIVATE_WORKFLOW_ENGINE_NAME}
      - export PRIVATE_UI_NAME=$${DEV_PRIVATE_UI_NAME}
      - export SESSION_NAME=$${DEV_SESSION_NAME}
      - export SESSION_SECRET=$${DEV_SESSION_SECRET}
      - export IMAGE_TAG=${DRONE_BUILD_NUMBER}
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
    when:
      branch:
        - master
      event:
        - push
        - deployment