pipeline:

  translation-service-test:
    image: node:8
    command:
      - npm install
      - npm test

  translation-service-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t translation-service .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+borders_central" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag translation-service quay.io/ukhomeofficedigital/translation-service:$${DRONE_COMMIT_SHA}
      - docker tag translation-service quay.io/ukhomeofficedigital/translation-service:latest
      - docker push quay.io/ukhomeofficedigital/translation-service:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/translation-service:latest
    when:
      branch: master
      event: push

